### ISSUE TITLE
Domain documentation

### ISSUE THREAD

**Issue by danlewis** [adventistmedia/simple_church#164]
Domains is now fully working. 
Scott can you read through what I've written on the domain page and have a go at following the instructions and then improving them so they make sense to you and everyone else.

**Comment by Scotttie** [comment]
Domains are a wild one to walk people through, there coudl be several different scenarios/skill levels.

I’ve had the first crack at it on the support page (no screen shots yet.) but no doubt I'll refine it, and add screen shots etc

Q's
1.	Do you have a better domain register we should use as an example/recommendation, instead of crazydomains I used.
2.	Do you have a more simple WhoIs (not commercial) lookup I can list also, instead of whois.com/whois which I mention in the ‘why isn’t it working’ checks at the end.
3.	I’m thinking the on screen ‘dashboard’ help note for domains you programmed in should be more brief, with just the minimum technical details listed for the pros, and then a prominent support link which goes to where we (I) can easily alter and screenshot etc as we go into the future. Something like:

[Domain shows here]
To connect this domain to your website, you need to have
1.	Purchased this domain 
2.	Setup a DNS CNAME record for [Domain shows here] that points to dns.adventist.place
For more comprehensive help on this task, visit http://place.adventistmedia.org.au/help/domains

**Comment by danlewis** [comment]
linked to support domain documentation/form
